# @package _global_

defaults:
  - override /data: relpose-angular

name: relpose-angular

eval_models:
  - pi3
  - vggt

eval_datasets:
  - Re10K
  - CO3Dv2

no_crop: False
load_img_size: 512

device: cuda

verbose: False

seed: 42

save_suffix: null
